name: Test

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Domain for the new site'
        required: true
      unique_name:
        description: 'Unique name for the configuration file'
        required: true
      path:
        description: 'Absolute path to the site root directory'
        required: true

jobs:
  create-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: SSH and Create Apache Site Config
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            DOMAIN=${{ github.event.inputs.domain }}
            UNIQUE_NAME=${{ github.event.inputs.unique_name }}
            SITE_PATH=${{ github.event.inputs.path }}

            # Create Apache site configuration
            APACHE_CONF="
            <VirtualHost *:80>
              ServerName $DOMAIN
              ServerAdmin web@webmaster.com
              DocumentRoot $SITE_PATH/public
              <Directory $SITE_PATH>
                AllowOverride All
              </Directory>
              ErrorLog \${APACHE_LOG_DIR}/error-$UNIQUE_NAME.log
              CustomLog \${APACHE_LOG_DIR}/access-$UNIQUE_NAME.log combined
            </VirtualHost>
            "

            # Create the configuration file on the server
            echo "$APACHE_CONF" | sudo tee /etc/apache2/sites-available/$UNIQUE_NAME.conf

            # Enable the site and reload Apache on the server
            sudo a2ensite $UNIQUE_NAME
            sudo systemctl reload apache2

            echo "Apache site for $DOMAIN has been created and enabled."
